In [7]:
import numpy as np
distance=[10,15,17,26]
time=[.30,.47,.55,1.20]

In [8]:
np_distance = np.array(distance)
np_time=np.array(time)

In [12]:
speed=np_distance/np_time


In [13]:
speed

array([33.33333333, 31.91489362, 30.90909091, 21.66666667])

In [14]:
np_city = np.array(['NYC','LA','Miami','Houston'])

In [15]:
np_city.ndim

1

In [16]:
np_city_with_state=np.array([['NYC','LA','Miami','Houston'],['NY','CA','FA','TA']])

In [17]:
np_city_with_state.ndim

2

In [18]:
np_city.shape

(4,)

In [19]:
np_city_with_state.shape

(2, 4)

In [20]:
np_city.size

4

In [21]:
np_city_with_state.size

8

In [22]:
np_city

array(['NYC', 'LA', 'Miami', 'Houston'], dtype='<U7')

In [23]:
np_city_with_state

array([['NYC', 'LA', 'Miami', 'Houston'],
       ['NY', 'CA', 'FA', 'TA']], dtype='<U7')

In [24]:
np_city_with_state.dtype

dtype('<U7')

In [25]:
first_trail_cyclist = [10,15,17,26]

In [26]:
second_trail_cyclist = [12,11,21,24]


In [27]:
np_first_trail_cyclist = np.array(first_trail_cyclist)


In [28]:
np_second_trail_cylist = np.array(second_trail_cyclist)

In [29]:
np_first_trail_cyclist+np_second_trail_cylist

array([22, 26, 38, 50])

In [30]:
cylist_trails = np.array([[10,15,17,26],[12,11,21,24]])

In [31]:
first_trail = cylist_trails[0]

In [32]:
first_trail

array([10, 15, 17, 26])

In [34]:
second_trail = cylist_trails[1]

In [35]:
second_trail

array([12, 11, 21, 24])

In [36]:
first_cylist_firstTrail = cylist_trails[0][0]

In [37]:
first_cylist_firstTrail

10

In [38]:
first_cylist_all_trails = cylist_trails[: , 0]

In [39]:
first_cylist_all_trails

array([10, 12])

In [40]:
cylist_trails.shape

(2, 4)

In [41]:
two_cylist_trail_data=cylist_trails[: ,1:3]

In [42]:
two_cylist_trail_data

array([[15, 17],
       [11, 21]])

In [43]:
cyclist_trails = np.array([[10,15,17,26],[12,11,21,24]])

In [45]:
two_cylist_trail_data=cylist_trails[: ,1:3]

In [46]:
two_cylist_trail_data

array([[15, 17],
       [11, 21]])

In [47]:
for iterate_cylist_trails_data in cylist_trails:
    print (iterate_cylist_trails_data)

[10 15 17 26]
[12 11 21 24]


In [55]:
for iterate_two_cylist_trail_data in two_cylist_trail_data:
    print (iterate_two_cylist_trail_data)

[15 17]
[11 21]


In [57]:
test_scores = np.array([[82,71,57,63],[54,68,81,45]])

In [60]:
passing_score = test_scores>60

In [62]:
passing_score

array([[ True,  True, False,  True],
       [False,  True,  True, False]])

In [63]:
test_scores[passing_score]

array([82, 71, 63, 68, 81])

In [64]:
NYC_Borough = np.array(['Manhattan','Bronx','Brooklyn','staten Island','Queens'])

In [65]:
NYC_Borough

array(['Manhattan', 'Bronx', 'Brooklyn', 'staten Island', 'Queens'],
      dtype='<U13')

In [66]:
Boroughs_in_NYC = NYC_Borough

In [67]:
Boroughs_in_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'staten Island', 'Queens'],
      dtype='<U13')

In [68]:
Boroughs_in_NYC is NYC_Borough

True

In [69]:
Boroughs_in_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'staten Island', 'Queens'],
      dtype='<U13')

In [70]:
View_of_Borough_in_NYC = Boroughs_in_NYC.view()

In [71]:
len(View_of_Borough_in_NYC)

5

In [72]:
View_of_Borough_in_NYC[4]='Central Park'

In [73]:
View_of_Borough_in_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'staten Island', 'Central Park'],
      dtype='<U13')

In [74]:
Boroughs_in_NYC

array(['Manhattan', 'Bronx', 'Brooklyn', 'staten Island', 'Central Park'],
      dtype='<U13')

In [75]:
copy_of_NYC_Borough = NYC_Borough.copy()

In [76]:
copy_of_NYC_Borough is NYC_Borough

False

In [77]:
copy_of_NYC_Borough.base is NYC_Borough

False

In [78]:
copy_of_NYC_Borough[4]='Central Park'

In [79]:
NYC_Borough

array(['Manhattan', 'Bronx', 'Brooklyn', 'staten Island', 'Central Park'],
      dtype='<U13')

In [80]:
copy_of_NYC_Borough

array(['Manhattan', 'Bronx', 'Brooklyn', 'staten Island', 'Central Park'],
      dtype='<U13')

In [81]:
np_sqrt = np.sqrt([2,4,9,16])

In [82]:
np_sqrt

array([1.41421356, 2.        , 3.        , 4.        ])

In [83]:
from numpy import pi 
np.cos(0)

1.0

In [84]:
np.sin(pi/2)

1.0

In [85]:
np.cos(pi)

-1.0

In [86]:
np.floor([1.5,1.6,2.7,3.3,1.1,-0.3,-1.4])

array([ 1.,  1.,  2.,  3.,  1., -1., -2.])

In [87]:
np.exp([0,1,5])

array([  1.        ,   2.71828183, 148.4131591 ])

In [88]:
new_cylist_trails = np.array([[10,15,17,26,13,19],[12,11,21,24,14,12]])

In [89]:
new_cylist_trails.ravel()

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 12])

In [90]:
new_cylist_trails.reshape(3,4)

array([[10, 15, 17, 26],
       [13, 19, 12, 11],
       [21, 24, 14, 12]])

In [91]:
new_cylist_trails.resize(2,6)

In [92]:
new_cylist_trails

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 12]])

In [93]:
np.hsplit(new_cylist_trails,2)

[array([[10, 15, 17],
        [12, 11, 21]]),
 array([[26, 13, 19],
        [24, 14, 12]])]

In [94]:
new_cylist_1 = np.array([10,15,17,26,13,19])

In [95]:
new_cylist_2 = np.array([12,11,21,24,14,23])

In [97]:
np.hstack((new_cylist_1, new_cylist_2))

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

In [98]:
import numpy as np

In [99]:
array_a = np.array([2, 3, 5, 8])
array_b = np.array([.3, .3, .3, .3])

In [100]:
array_a * array_b

array([0.6, 0.9, 1.5, 2.4])

In [101]:
scalar_c = .3

In [102]:
array_a * scalar_c

array([0.6, 0.9, 1.5, 2.4])

In [103]:
import numpy as np

In [104]:
array_a = np.array([2, 3, 5, 8])
array_b = np.array([.3, .3, .3, .3])

In [105]:
array_a * array_b

array([0.6, 0.9, 1.5, 2.4])

In [107]:
array_d = np.array([4,3])

In [108]:
array_a * array_d

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [110]:
np_week_one = np.array([105, 135, 195, 120, 165])
np_week_two = np.array([123, 156, 230, 200, 147])

In [114]:
total_earning = np_week_one+np_week_two

NameError: name 'np_week_one' is not defined

In [116]:
test_scores =np.array([[83,71,57,63],[54,68,81,45]])

In [117]:
test_scores.transpose()

array([[83, 54],
       [71, 68],
       [57, 81],
       [63, 45]])

In [118]:
inverse_array =np.array([[10,20],[15,25]])

In [119]:
np.linalg.inv(inverse_array)

array([[-0.5,  0.4],
       [ 0.3, -0.2]])

In [120]:
trace_array =np.array([[10,20],[22,31]])

In [121]:
np.trace(trace_array)

41