In [1]:
from scipy.integrate import quad
#Integration

In [2]:
def integrateFunction(x):
    return x

In [4]:
quad(integrateFunction,0,1)

(0.5, 5.551115123125783e-15)

In [5]:
def integrateFn(x,a,b):
    return x*a+b

In [6]:
a=3 
b=2

In [7]:
quad(integrateFn,0,1,args=(a,b))

(3.5, 3.885780586188048e-14)

In [8]:
import scipy.integrate as integrate

In [11]:
def f(x, y):
    return x + y
integrate.dblquad(f, 0, 1,lambda x: 0, lambda x: 2)

(3.0, 4.436070580899685e-14)

In [12]:
import numpy as np
from scipy import optimize
#optimization

In [14]:
def f(x):
    return x**2 + 5*np.sin(x)

In [15]:
minimaValue = optimize.minimize(f,x0=2,method='bfgs' ,options={'disp':True})

Optimization terminated successfully.
         Current function value: -3.246394
         Iterations: 5
         Function evaluations: 18
         Gradient evaluations: 9


In [18]:
minimaValueWithoutOpt = optimize.minimize(f ,x0=2,method='bfgs')

In [19]:
minimaValueWithoutOpt

      fun: -3.2463942726915214
 hess_inv: array([[0.15445818]])
      jac: array([-4.76837158e-07])
  message: 'Optimization terminated successfully.'
     nfev: 18
      nit: 5
     njev: 9
   status: 0
  success: True
        x: array([-1.11051058])

In [20]:
#lINEAR ALGEBRA
#Inverse of matrix
import numpy as np
from scipy import linalg
matrix = np.array([[10,6],[2,7]])
matrix

array([[10,  6],
       [ 2,  7]])

In [21]:
type(matrix)

numpy.ndarray

In [22]:
linalg.inv(matrix)

array([[ 0.12068966, -0.10344828],
       [-0.03448276,  0.17241379]])

In [23]:
#finding deterniant
import numpy as np
from scipy import linalg
matrix = np.array([[4,9],[3,5]])
matrix

array([[4, 9],
       [3, 5]])

In [24]:
linalg.det(matrix)

-7.000000000000001

In [26]:
#Slove linear systems
import numpy as np
from scipy import linalg

In [32]:
numArray = np.array([[2,3,1],[-1,5,4],[3,2,9]])

In [33]:
numArrValue = np.array([21,9,6])

In [35]:
linalg.solve(numArray,numArrValue)

array([ 4.95,  4.35, -1.95])

In [36]:
#single value decomposition(SVD)
import numpy as np
from scipy import linalg

In [37]:
numSvdArr = np.array([[3,5,1],[9,5,7]])

In [38]:
numSvdArr.shape

(2, 3)

In [39]:
linalg.svd(numSvdArr)

(array([[-0.37879831,  0.92547925],
        [-0.92547925, -0.37879831]]),
 array([13.38464336,  3.29413449]),
 array([[-0.7072066 , -0.4872291 , -0.51231496],
        [-0.19208294,  0.82977932, -0.52399467],
        [-0.68041382,  0.27216553,  0.68041382]]))

In [40]:
#Statistics
from scipy.stats import norm

In [41]:
norm.rvs(loc=0,scale=1,size=10)

array([-1.38900314, -2.08949598,  0.65549404, -1.41833151, -1.01597645,
       -1.24761418, -0.513848  , -1.71513758,  1.21581252, -0.5009397 ])

In [42]:
norm.cdf(5,loc=1,scale=2)

0.9772498680518208

In [43]:
norm.pdf(9,loc=0,scale=1)

1.0279773571668917e-18